Unbreak account_open_metadata
all_entries_by_type doesn't exist, leading to breakage:

        for entry in accapi.all_entries_by_type[Open]:
    AttributeError: 'FavaInvestorAPI' object has no attribute 'all_entries_by_type'

Fixes #35